"""The names the schema *actually* carries in PostgreSQL, against the ones it declares.

Revision ``0010`` renamed eighteen check constraints across eight tables whose
names had landed in the database with their prefix doubled --
``ck_budget_target_ck_budget_target_amount_positive`` -- because revisions
``0005`` and ``0006`` declared a constraint as ``name="ck_budget_target_amount_
positive"`` when the naming template on ``Base.metadata`` is already
``ck_%(table_name)s_%(constraint_name)s``. The declared string is a *component*
of the final name, not the whole of it. Four of the eighteen went past
PostgreSQL's 63-character limit and were truncated by SQLAlchemy to a stem plus a
four-hex-digit hash, so their deployed names could not be derived by reading any
source file -- only by querying ``pg_constraint``.

Nothing in the repository could see it. The model reads correctly, the migrations
read correctly, and the tests were green: the divergence existed only in the
PostgreSQL catalogue, where it left every deployed constraint unaddressable by
name -- no ``IntegrityError`` handler can map a violated constraint to a message,
and no later revision can alter one without hardcoding a truncation hash.

Autogenerate does not close the hole, in either direction, and both halves of
that were measured against this schema rather than assumed:

* it does not compare check constraints at all, so a doubled ``ck`` name leaves
  ``alembic check`` perfectly clean -- all eighteen were invisible to it;
* where it *does* compare a name -- a unique constraint, an index -- it reports a
  ``remove_constraint`` followed by an identical-looking ``add_constraint``, on
  every run, and the diff it prints does not contain either name. The symptom is
  visible; the cause is not.

So this file compares the **catalogue to the model** -- not the migrations to the
model, and not autogenerate's opinion of either. That is the only comparison that
sees what truncation produced, because truncation happens when the DDL is
emitted, after every source file has had its say.

Two guards, and each one has a test that watches it fail:

* :func:`test_the_catalogue_matches_the_model` walks ``pg_constraint`` and
  ``pg_index`` on a database migrated to ``head`` and diffs the names against
  what ``Base.metadata`` renders. It catches a migration that drifted from the
  model, whatever the cause.
* :func:`test_declared_names_do_not_repeat_the_template_prefix` reads the model
  alone. It catches the doubling in the case the first guard cannot see -- the
  one where the *model* carries the doubled name too, so the database agrees with
  it and the diff is empty.

Both cover the five naming families (``ck``, ``uq``, ``fk``, ``pk``, ``ix``).
Only the ``ck`` template interpolates ``%(constraint_name)s`` today, so only
``ck`` can double; checking the other four costs a few lines and survives a
change to the convention, which
:func:`test_every_naming_family_is_covered` makes mandatory.
"""

from __future__ import annotations

from collections.abc import Iterable
from dataclasses import dataclass
from pathlib import Path
from typing import Final

import pytest
from alembic import command
from alembic.config import Config
from alembic.util import AutogenerateDiffsDetected
from sqlalchemy import (
    CheckConstraint,
    Column,
    ForeignKeyConstraint,
    Integer,
    MetaData,
    Numeric,
    PrimaryKeyConstraint,
    Table,
    UniqueConstraint,
    text,
)
from sqlalchemy.dialects import postgresql
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.schema import conv

from chaudron.domain.models import _ALLERGENS_RISK_SQL, NAMING_CONVENTION, Base

#: The PostgreSQL identifier preparer -- the object that decides what a name looks
#: like once it reaches the database, truncation included. Asking it rather than
#: reimplementing its rule is the whole reason this guard can tell a legitimate
#: truncation from a doubled prefix.
#:
#: ``Dialect.__init__`` carries no annotations, hence the ignore; the preparer it
#: returns is typed.
_PREPARER: Final = postgresql.dialect().identifier_preparer  # type: ignore[no-untyped-call]

_FAMILIES: Final[tuple[str, ...]] = ("pk", "fk", "uq", "ck", "ix")

_FAMILY_BY_CONSTRAINT_TYPE: Final[dict[type, str]] = {
    PrimaryKeyConstraint: "pk",
    ForeignKeyConstraint: "fk",
    UniqueConstraint: "uq",
    CheckConstraint: "ck",
}

#: ``pg_constraint.contype`` to naming family.
_FAMILY_BY_CONTYPE: Final[dict[str, str]] = {"p": "pk", "f": "fk", "u": "uq", "c": "ck"}

#: Floors on how many names a scan must find before its verdict is worth
#: anything. They are not an inventory of the schema: they sit at roughly half of
#: what it carries today, so ordinary growth never touches them.
#:
#: They exist because of the way this class of test fails silently. A scan that
#: finds nothing -- a catalogue query that lost its schema filter, a metadata
#: import that resolved to an empty ``Base`` -- produces an empty diff, and an
#: empty diff reads exactly like "no mismatch". The suite would then certify a
#: schema it never looked at. Lowering a floor is a deliberate edit, which is the
#: review conversation this constant exists to force.
_MINIMUM_NAMES_PER_FAMILY: Final[dict[str, int]] = {
    "pk": 15,
    "fk": 25,
    "uq": 5,
    "ck": 15,
    "ix": 15,
}

_MINIMUM_NAMES_TOTAL: Final = 100

#: ``backend/``, holding ``alembic.ini`` and ``migrations/``.
_BACKEND_ROOT: Final = Path(__file__).resolve().parent.parent


# --------------------------------------------------------------------------- #
# What a name is, on each side
# --------------------------------------------------------------------------- #


@dataclass(frozen=True, slots=True, order=True)
class SchemaName:
    """One constraint or index name, spelled as PostgreSQL stores it."""

    table: str
    family: str
    name: str

    def __str__(self) -> str:
        return f"{self.table}.{self.name} ({self.family})"


@dataclass(frozen=True, slots=True)
class DeclaredName:
    """What the model renders for one constraint or index, before and after truncation.

    ``full`` is what the naming template produces, of any length. ``stored`` is
    what PostgreSQL will actually hold: ``full``, truncated by the dialect when it
    exceeds 63 characters.

    **Legitimate truncation is not an offence, and this is where the two cases are
    kept apart.** SQLAlchemy truncates deterministically -- a stem plus the last
    four hex digits of the md5 of the full name -- and applies that same rule when
    a migration emits the DDL. Both sides therefore land on the same string, which
    is why the two foreign keys of ``recipe_suggestion_ingredient`` compare equal
    despite being cut short, and why the comparison below is made on ``stored``
    rather than on ``full``. A doubled prefix, in contrast, produces a *different*
    string on each side and still fails.

    Do not "simplify" this by comparing ``full`` on both sides: ``full`` is a
    property of the model only, so that would compare the model with itself and
    the guard would pass on every database ever built.
    """

    table: str
    family: str
    full: str
    stored: str

    @property
    def key(self) -> SchemaName:
        return SchemaName(self.table, self.family, self.stored)


def _render(name: str, family: str) -> str:
    """Apply the dialect's truncation rule to a convention-rendered name."""
    label = conv(name)
    if family == "ix":
        return _PREPARER.truncate_and_render_index_name(label, _alembic_quote=False)
    return _PREPARER.truncate_and_render_constraint_name(label, _alembic_quote=False)


def _declared_names(metadata: MetaData) -> tuple[DeclaredName, ...]:
    """Every constraint and index name the metadata renders, in both spellings.

    Nothing here can come out unnamed. A check constraint declared without a
    ``name=`` raises at import time -- the ``ck`` template interpolates
    ``%(constraint_name)s`` and SQLAlchemy refuses to render it from nothing --
    and the other four templates build a name out of the table and its columns.
    The assertions below are therefore a statement of that fact, not a branch
    anyone is expected to reach.
    """
    collected: list[DeclaredName] = []
    for table in metadata.sorted_tables:
        for constraint in table.constraints:
            family = _FAMILY_BY_CONSTRAINT_TYPE.get(type(constraint))
            if family is None:  # pragma: no cover - no other constraint type is used
                continue
            assert constraint.name is not None, f"{table.name}: unnamed {family} constraint"
            full = str(constraint.name)
            collected.append(DeclaredName(table.name, family, full, _render(full, family)))
        for index in table.indexes:
            assert index.name is not None, f"{table.name}: unnamed index"
            full = str(index.name)
            collected.append(DeclaredName(table.name, "ix", full, _render(full, "ix")))
    return tuple(collected)


_MODEL_NAMES: Final[tuple[DeclaredName, ...]] = _declared_names(Base.metadata)
_MODEL_TABLES: Final[frozenset[str]] = frozenset(Base.metadata.tables)


# --------------------------------------------------------------------------- #
# The catalogue
# --------------------------------------------------------------------------- #

# `contype` is cast to text because asyncpg hands back PostgreSQL's `"char"` type
# as raw bytes, which compares equal to nothing.
_CATALOGUE_CONSTRAINTS: Final = text("""
    SELECT t.relname AS table_name, c.conname AS name, c.contype::text AS contype
    FROM pg_constraint AS c
    JOIN pg_class AS t ON t.oid = c.conrelid
    JOIN pg_namespace AS n ON n.oid = t.relnamespace
    WHERE n.nspname = current_schema()
      AND t.relkind = 'r'
      AND c.contype IN ('p', 'f', 'u', 'c')
""")

# Indexes that back a primary key or a unique constraint are already counted as
# constraints above; listing them again would report every one of them twice.
_CATALOGUE_INDEXES: Final = text("""
    SELECT t.relname AS table_name, i.relname AS name
    FROM pg_index AS x
    JOIN pg_class AS i ON i.oid = x.indexrelid
    JOIN pg_class AS t ON t.oid = x.indrelid
    JOIN pg_namespace AS n ON n.oid = i.relnamespace
    WHERE n.nspname = current_schema()
      AND t.relkind = 'r'
      AND NOT EXISTS (SELECT 1 FROM pg_constraint AS c WHERE c.conindid = i.oid)
""")


async def _catalogue_names(session: AsyncSession) -> frozenset[SchemaName]:
    """What PostgreSQL holds, restricted to the tables the model declares.

    ``alembic_version`` is Alembic's own bookkeeping and is not part of the model,
    so it is filtered out here rather than exempted by name further down.
    """
    collected: set[SchemaName] = set()
    for row in (await session.execute(_CATALOGUE_CONSTRAINTS)).all():
        if row.table_name in _MODEL_TABLES:
            collected.add(SchemaName(row.table_name, _FAMILY_BY_CONTYPE[row.contype], row.name))
    for row in (await session.execute(_CATALOGUE_INDEXES)).all():
        if row.table_name in _MODEL_TABLES:
            collected.add(SchemaName(row.table_name, "ix", row.name))
    return frozenset(collected)


# --------------------------------------------------------------------------- #
# The two detectors
# --------------------------------------------------------------------------- #

_WHY: Final = (
    "The naming template already adds the {prefix!r} prefix, so it must not appear in "
    "the name you declare: `ck` renders as {template!r}, which makes the declared string "
    "a *component* of the final name rather than the whole of it."
)


def _doubled_form(entry: SchemaName) -> SchemaName:
    """The name a declaration lands on when it repeats the template's prefix.

    A check constraint meant to be ``ck_budget_target_amount_positive``, declared
    as ``name="ck_budget_target_amount_positive"`` instead of
    ``name="amount_positive"``, reaches PostgreSQL as
    ``ck_budget_target_ck_budget_target_amount_positive`` -- truncated here by the
    same preparer that truncated it on the way in, so the four names that went
    past 63 characters are recognised too, hash and all.
    """
    doubled = f"{entry.family}_{entry.table}_{entry.name}"
    return SchemaName(entry.table, entry.family, _render(doubled, entry.family))


def _describe_mismatches(
    catalogue: frozenset[SchemaName], declared: Iterable[DeclaredName]
) -> list[str]:
    """One actionable line per name the database and the model disagree on."""
    expected = {entry.key for entry in declared}
    only_in_database = sorted(catalogue - expected)
    only_in_model = sorted(expected - catalogue)

    # Pair an unexpected database name with the model name it would have come from,
    # had the declaration repeated the template's prefix. This is what turns
    # "ck_shelf_life_guideline_ck_shelf_life_guideline_duratio_eb80" -- a string
    # derivable from no source file -- back into a diagnosis.
    origin_of: dict[SchemaName, SchemaName] = {
        _doubled_form(entry): entry for entry in only_in_model
    }

    lines: list[str] = []
    for entry in only_in_database:
        origin = origin_of.get(entry)
        prefix = f"{entry.family}_{entry.table}_"
        if origin is None:
            lines.append(
                f"{entry.table}: the database holds {entry.name!r} ({entry.family}) and the "
                f"model declares no such name. Either declare it in domain/models.py, or "
                f"drop it in a migration -- a constraint the model cannot name is a "
                f"constraint nothing in the application can address."
            )
            continue
        component = origin.name.removeprefix(prefix)
        lines.append(
            f"{entry.table}: the database holds {entry.name!r} where the model renders "
            f"{origin.name!r}. "
            + _WHY.format(prefix=prefix, template=NAMING_CONVENTION[entry.family])
            + f" Declare name={component!r}. Renaming an already-deployed constraint takes "
            f'a migration of its own -- `ALTER TABLE "{entry.table}" RENAME CONSTRAINT '
            f'"{entry.name}" TO "{origin.name}"`, as revision 0010 does.'
        )

    for entry in only_in_model:
        if _doubled_form(entry) in catalogue:
            continue  # already reported above, from the database's side
        prefix = f"{entry.family}_{entry.table}_"
        line = (
            f"{entry.table}: the model renders {entry.name!r} ({entry.family}) and the "
            f"database has no constraint or index by that name. A migration is missing, or "
            f"the one that created it used a name of its own."
        )
        # The mirror image of the case above: here it is the *model* that carries the
        # doubled name, and the database that holds the sane one.
        if entry.name.startswith(prefix * 2):
            line += (
                " "
                + _WHY.format(prefix=prefix, template=NAMING_CONVENTION[entry.family])
                + f" Declare name={entry.name[len(prefix) * 2 :]!r}."
            )
        lines.append(line)
    return lines


def _prefix_doublings(declared: Iterable[DeclaredName]) -> list[str]:
    """Declared names that already carried the prefix their template adds.

    Read from the model alone, so it fires before the mistake is ever migrated --
    and it fires in the one case :func:`_describe_mismatches` is blind to, where
    the model carries the doubled name as well and the database dutifully agrees.
    """
    offenders: list[str] = []
    for entry in declared:
        prefix = f"{entry.family}_{entry.table}_"
        if not entry.full.startswith(prefix * 2):
            continue
        offenders.append(
            f"{entry.table}: the {entry.family} name renders as {entry.full!r}. "
            + _WHY.format(prefix=prefix, template=NAMING_CONVENTION[entry.family])
            + f" Declare name={entry.full[len(prefix) * 2 :]!r} and the template will make it "
            f"{entry.full[len(prefix) :]!r}."
        )
    return offenders


def _assert_scan_is_plausible(names: Iterable[SchemaName], source: str) -> None:
    """Refuse to draw a conclusion from a scan that plainly read nothing.

    Raises ``AssertionError`` -- it is called from the tests it protects, and its
    failure must be their failure.
    """
    found = list(names)
    counts = {family: sum(1 for entry in found if entry.family == family) for family in _FAMILIES}
    assert len(found) >= _MINIMUM_NAMES_TOTAL, (
        f"the {source} scan found only {len(found)} names ({counts}), which is fewer than "
        f"{_MINIMUM_NAMES_TOTAL}. Nothing below this line is trustworthy: an empty scan "
        f"produces an empty diff, and an empty diff reads exactly like agreement. Fix the "
        f"scan, or lower _MINIMUM_NAMES_TOTAL on purpose if the schema really shrank."
    )
    short = {
        family: counts[family]
        for family, minimum in _MINIMUM_NAMES_PER_FAMILY.items()
        if counts[family] < minimum
    }
    assert not short, (
        f"the {source} scan found too few names in {short} (floors: "
        f"{_MINIMUM_NAMES_PER_FAMILY}). A family that collects nothing is a family this "
        f"guard silently stops covering."
    )


# --------------------------------------------------------------------------- #
# The guards
# --------------------------------------------------------------------------- #


def test_every_naming_family_is_covered() -> None:
    """A sixth template must not slip past this file unnoticed."""
    assert set(NAMING_CONVENTION) == set(_FAMILIES), (
        f"NAMING_CONVENTION declares {sorted(NAMING_CONVENTION)} and this guard covers "
        f"{sorted(_FAMILIES)}. Extend _FAMILIES, _FAMILY_BY_CONSTRAINT_TYPE, "
        f"_FAMILY_BY_CONTYPE and _MINIMUM_NAMES_PER_FAMILY, so the new family is compared "
        f"against the catalogue like the others."
    )


def test_the_model_scan_is_not_empty() -> None:
    """The floor, asserted on its own so a broken scan is reported as a broken scan."""
    _assert_scan_is_plausible((entry.key for entry in _MODEL_NAMES), source="model")


def test_declared_names_do_not_repeat_the_template_prefix() -> None:
    _assert_scan_is_plausible((entry.key for entry in _MODEL_NAMES), source="model")
    offenders = _prefix_doublings(_MODEL_NAMES)
    assert not offenders, "\n".join(["doubled name prefixes in the model:", *offenders])


async def test_the_catalogue_matches_the_model(db_session: AsyncSession) -> None:
    """Every name PostgreSQL holds is a name the model renders, and the reverse.

    The migrations are not read here. They are the thing under suspicion: each one
    of them was correct on its own terms, and the schema still drifted.
    """
    catalogue = await _catalogue_names(db_session)
    _assert_scan_is_plausible(catalogue, source="catalogue")
    _assert_scan_is_plausible((entry.key for entry in _MODEL_NAMES), source="model")

    mismatches = _describe_mismatches(catalogue, _MODEL_NAMES)
    assert not mismatches, "\n".join(
        ["the deployed schema and domain/models.py disagree on these names:", *mismatches]
    )


def test_the_migrations_leave_nothing_for_autogenerate_to_propose(
    initialised_database: str,
) -> None:
    """``alembic check`` on a database at ``head``: the drift this file does *not* cover.

    A backstop, not the guard. It was measured, not assumed: doubling a ``ck`` name
    in the model leaves this test green, because autogenerate never compares check
    constraints -- which is precisely why the guards above read ``pg_constraint``
    themselves. What it does catch is everything else that makes the model and the
    migrations describe different schemas: a forgotten column, a widened numeric, a
    renamed unique constraint or index. Cheap here, since the database is already
    migrated, and it is the command a developer would run by hand after editing the
    model.

    **Its second blind spot is computed columns**, and it announces it: this test is
    the source of the suite's only warning, *"Computed default on
    product.allergens_risk cannot be modified"*. Autogenerate skips generation
    expressions, so an edit to the ``CASE`` that decides whether a product is
    withheld from someone allergic to it would leave this green. That gap is covered
    by ``test_the_generated_column_still_computes_what_the_model_declares`` below,
    which compares the deployed expression against the model's declaration through
    PostgreSQL's own normaliser -- and by its companion, which proves the comparison
    can tell a changed expression from an unchanged one.

    Its diff is not actionable on its own. A renamed unique constraint is reported
    as a ``remove_constraint``/``add_constraint`` pair that prints columns and no
    names at all, which is why the failure message sends the reader upwards.

    Synchronous on purpose: ``migrations/env.py`` calls ``asyncio.run`` itself, so
    an ``async def`` test here would fail with "cannot be called from a running
    event loop" and say nothing about the schema.
    """
    # `Config()` with no file, options set by hand, rather than `Config(alembic.ini)`.
    # `migrations/env.py` calls `fileConfig(config.config_file_name)` whenever there
    # is one, and `fileConfig` disables every logger the file does not name --
    # `alembic.ini` names root, sqlalchemy and alembic, so `chaudron.seed` and the
    # rest come out of this call silenced for the remainder of the process. Three
    # tests in `test_seed_guard.py` then read an empty `caplog` and fail somewhere
    # else entirely. A test must not reconfigure the logging of the run it is part
    # of; leaving `config_file_name` at `None` is the whole fix, and the two options
    # below are all `check` needs from that file.
    config = Config()
    config.set_main_option("script_location", str(_BACKEND_ROOT / "migrations"))
    config.set_main_option("sqlalchemy.url", initialised_database)
    try:
        command.check(config)
    except AutogenerateDiffsDetected as detected:
        pytest.fail(
            f"`alembic check` is not clean against a database at head: {detected}. The model "
            f"and the migrations describe different schemas -- write the missing revision. "
            f"If the difference is a constraint *name*, read "
            f"test_the_catalogue_matches_the_model above before writing anything."
        )


# --------------------------------------------------------------------------- #
# Guards on the guards
# --------------------------------------------------------------------------- #


def test_the_plausibility_floor_rejects_an_empty_scan() -> None:
    """The guard that keeps the guard from passing on nothing.

    A census test that reads an empty collection concludes that every member of it
    is compliant. This suite has been bitten by exactly that shape once already --
    a route inventory that enumerated zero routes and certified them all
    authenticated -- so the floor gets a test of its own rather than trust.
    """
    with pytest.raises(AssertionError, match="found only 0 names"):
        _assert_scan_is_plausible([], source="deliberately empty")

    one_family_missing = [entry.key for entry in _MODEL_NAMES if entry.family != "ck"]
    with pytest.raises(AssertionError, match="too few names"):
        _assert_scan_is_plausible(one_family_missing, source="deliberately partial")


def test_the_model_guard_fails_on_a_doubled_name() -> None:
    """Build the mistake and watch the detector catch it.

    A throwaway ``MetaData`` carrying the project's own naming convention, and a
    check constraint declared the way revisions ``0005`` and ``0006`` declared
    theirs. Nothing here touches ``Base.metadata``.
    """
    metadata = MetaData(naming_convention=NAMING_CONVENTION)
    Table(
        "naming_guard_probe",
        metadata,
        Column("id", Integer, primary_key=True),
        Column("amount", Numeric(12, 2), nullable=False),
        # The mistake, verbatim: the prefix the template adds, typed by hand into
        # the name the template is given.
        CheckConstraint("amount > 0", name="ck_naming_guard_probe_amount_positive"),
    )

    declared = _declared_names(metadata)
    doubled = next(entry for entry in declared if entry.family == "ck")
    assert doubled.full == "ck_naming_guard_probe_ck_naming_guard_probe_amount_positive", (
        "the convention no longer doubles a pre-prefixed name; if that is deliberate, this "
        "whole file is about a mistake that can no longer be made"
    )

    offenders = _prefix_doublings(declared)
    assert len(offenders) == 1
    assert "ck_naming_guard_probe_ck_naming_guard_probe_amount_positive" in offenders[0]
    assert "already adds the 'ck_naming_guard_probe_' prefix" in offenders[0]
    assert "Declare name='amount_positive'" in offenders[0]

    # And the healthy declaration is not reported.
    assert not _prefix_doublings(entry for entry in declared if entry.family != "ck"), (
        "a name that does not repeat its prefix must never be reported"
    )


#: The four names that went past 63 characters, ``(table, intended, deployed)``,
#: as revision ``0010`` read them out of ``pg_constraint`` on a database migrated
#: to ``0009``. Observations, not configuration: they were not transcribed from
#: any source file, because no source file contains them.
_HISTORICAL_TRUNCATIONS: Final[tuple[tuple[str, str, str], ...]] = (
    (
        "infant_food_restriction",
        "ck_infant_food_restriction_bands_present",
        "ck_infant_food_restriction_ck_infant_food_restriction_b_df82",
    ),
    (
        "infant_food_restriction",
        "ck_infant_food_restriction_matcher_present",
        "ck_infant_food_restriction_ck_infant_food_restriction_m_21e9",
    ),
    (
        "recipe_suggestion",
        "ck_recipe_suggestion_feedback_matches_status",
        "ck_recipe_suggestion_ck_recipe_suggestion_feedback_matc_96f3",
    ),
    (
        "shelf_life_guideline",
        "ck_shelf_life_guideline_durations_positive",
        "ck_shelf_life_guideline_ck_shelf_life_guideline_duratio_eb80",
    ),
)


@pytest.mark.parametrize(
    ("table", "intended", "deployed"),
    _HISTORICAL_TRUNCATIONS,
    ids=[intended for _, intended, _deployed in _HISTORICAL_TRUNCATIONS],
)
def test_the_diagnosis_reproduces_the_names_that_were_actually_deployed(
    table: str, intended: str, deployed: str
) -> None:
    """The truncated four, the ones no reader could have derived, paired back by hand.

    This is what makes the failure message worth reading rather than merely true.
    ``_doubled_form`` has to reproduce SQLAlchemy's truncation exactly -- the stem
    cut at 55 characters plus an underscore and four hex digits of an md5 taken
    over the *full* name -- or a doubled long name would be reported as two
    unrelated strings ("the database has this, the model has that") and the reader
    would be back to querying the catalogue to work out which is which.

    Measured against the real deployment, so a future SQLAlchemy that changes its
    truncation rule fails here, loudly, instead of quietly degrading the diagnosis.
    """
    assert _doubled_form(SchemaName(table, "ck", intended)).name == deployed


async def test_the_catalogue_guard_fails_on_a_doubled_name(db_session: AsyncSession) -> None:
    """Reproduce the deployed bug on a real constraint, and watch the diff catch it.

    PostgreSQL rolls DDL back like anything else and ``db_session`` rolls back, so
    the rename lives for the length of this test and leaves the session's database
    exactly as it found it.

    The victim is chosen from the model rather than hardcoded: naming this file's
    proof after one particular constraint would make it fail the day that
    constraint is legitimately renamed, and a guard that fails for the wrong reason
    gets deleted.
    """
    victim = min(entry.key for entry in _MODEL_NAMES if entry.family == "ck")
    doubled = _doubled_form(victim)

    before = await _catalogue_names(db_session)
    assert victim in before, f"{victim} is not in the catalogue; the probe would prove nothing"
    assert not _describe_mismatches(before, _MODEL_NAMES), "the schema is already mismatched"

    # Identifiers are quoted rather than interpolated bare: they come from the
    # model's own metadata, so there is nothing to inject, and quoting is the form
    # that keeps working if a name ever needs it.
    await db_session.execute(
        text(f'ALTER TABLE "{victim.table}" RENAME CONSTRAINT "{victim.name}" TO "{doubled.name}"')
    )

    after = await _catalogue_names(db_session)
    assert doubled in after
    mismatches = _describe_mismatches(after, _MODEL_NAMES)

    assert len(mismatches) == 1, f"expected exactly one offence, got {mismatches}"
    report = mismatches[0]
    assert doubled.name in report, "the failure must name what is in the database"
    assert victim.name in report, "the failure must name what the model expects"
    assert f"already adds the 'ck_{victim.table}_' prefix" in report, (
        "the failure must say *why*, or the next reader has to reconstruct this file"
    )
    assert "RENAME CONSTRAINT" in report, "the failure must say how to repair a deployed database"


async def test_the_generated_column_still_computes_what_the_model_declares(
    db_session: AsyncSession,
) -> None:
    """The one drift ``alembic check`` above cannot see, and the riskiest to miss.

    Autogenerate refuses to compare computed defaults -- it says so out loud, as the
    suite's only warning: *"Computed default on product.allergens_risk cannot be
    modified"*. So the backstop that catches a forgotten column or a widened numeric
    is blind to the expression behind the single column that decides whether a
    product is withheld from someone who is allergic to it. A migration editing that
    ``CASE`` would leave every test in this file green.

    Comparing the two as *text* would be a test that fails on whitespace: PostgreSQL
    stores its own normalised rendering of the expression, not the string it was
    given. So the model's declaration is handed to PostgreSQL on a throwaway table
    and read back through the same normaliser. Both sides come out in the server's
    spelling, and what is left to compare is the meaning.

    ``tests/domain/test_allergen_unknown_is_not_safe.py`` covers the *behaviour* --
    that an undocumented product carries all fourteen allergens and is excluded by
    the obvious query. This covers the narrower thing that survives a subtler edit:
    that the deployed expression is still the declared one, including the branch a
    behavioural test might not happen to exercise.
    """
    deployed = await db_session.scalar(
        text(
            "SELECT generation_expression FROM information_schema.columns"
            " WHERE table_name = 'product' AND column_name = 'allergens_risk'"
        )
    )
    assert deployed, "product.allergens_risk is no longer a generated column"

    # Same expression, same server, same normaliser -- on a table that disappears
    # with this transaction's rollback.
    await db_session.execute(
        text(
            "CREATE TABLE _drift_probe ("
            " allergen_state allergen_data_state NOT NULL DEFAULT 'unknown',"
            " allergens_contains allergen[] NOT NULL DEFAULT '{}',"
            " allergens_may_contain allergen[] NOT NULL DEFAULT '{}',"
            f" allergens_risk allergen[] GENERATED ALWAYS AS ({_ALLERGENS_RISK_SQL}) STORED"
            ")"
        )
    )
    declared = await db_session.scalar(
        text(
            "SELECT generation_expression FROM information_schema.columns"
            " WHERE table_name = '_drift_probe' AND column_name = 'allergens_risk'"
        )
    )

    assert deployed == declared, (
        "product.allergens_risk no longer computes what domain/models.py declares.\n"
        f"deployed: {deployed}\ndeclared: {declared}\n"
        "`alembic check` cannot see this: it skips computed defaults. If the change "
        "is deliberate, write the revision that applies it to `product` too."
    )


async def test_the_generated_column_guard_notices_a_changed_expression(
    db_session: AsyncSession,
) -> None:
    """Build the drift and watch the detector catch it.

    A comparison of two strings the server produced could pass by being vacuous --
    both ``None``, or both normalised into the same thing regardless of input. The
    mutation here is the plausible one rather than an absurd one: dropping
    ``allergens_may_contain`` from the declared branch, which is how "may contain
    traces" quietly stops counting as a risk while every row still looks populated.
    """
    honest = _ALLERGENS_RISK_SQL
    drifted = honest.replace(" || allergens_may_contain", "")
    assert drifted != honest, "the mutation did not change the expression"

    await db_session.execute(
        text(
            "CREATE TABLE _drift_probe_mutated ("
            " allergen_state allergen_data_state NOT NULL DEFAULT 'unknown',"
            " allergens_contains allergen[] NOT NULL DEFAULT '{}',"
            " allergens_may_contain allergen[] NOT NULL DEFAULT '{}',"
            f" allergens_risk allergen[] GENERATED ALWAYS AS ({drifted}) STORED"
            ")"
        )
    )
    mutated = await db_session.scalar(
        text(
            "SELECT generation_expression FROM information_schema.columns"
            " WHERE table_name = '_drift_probe_mutated' AND column_name = 'allergens_risk'"
        )
    )
    deployed = await db_session.scalar(
        text(
            "SELECT generation_expression FROM information_schema.columns"
            " WHERE table_name = 'product' AND column_name = 'allergens_risk'"
        )
    )

    assert mutated, "the probe table did not produce a generation expression"
    assert mutated != deployed, (
        "the guard above cannot tell a changed expression from the deployed one, "
        "so its passing says nothing"
    )
