import { useState } from 'react';
import { describeError } from '../../api/client';
import { confirmReceipt, discardReceipt } from '../../api/endpoints';
import type { Receipt, ReceiptConfirmResult, StorageLocation } from '../../api/types';
import { Button, Callout, Field } from '../../components/ui';
import { controlClass } from '../../components/controlClass';
// `money.ts` lives under `features/budget` because that is where it was first
// needed, and it is the application's only decimal-money code: centimes in
// `BigInt`, `Intl` at the last step. A second copy here would be a second
// rounding rule on the two screens that must agree about what was spent.
import { formatMoney, toCentimes } from '../budget/money';
import { ReceiptLineRow } from './ReceiptLineRow';
import {
  receiptDraftError,
  toReceiptConfirmLines,
  toReceiptDrafts,
  type ReceiptDraftLine,
} from './receiptReview';
import styles from './Receipts.module.css';

interface Props {
  receipt: Receipt;
  locations: StorageLocation[];
  onCancelled: () => void;
  onConfirmed: (result: ReceiptConfirmResult) => void;
}

function plural(count: number, one: string, many: string): string {
  return count > 1 ? many : one;
}

/** An amount, in French, or an em dash when the receipt did not carry one. */
function money(value: string | null, currency: string | null): string {
  if (value === null) return '—';
  return currency === null ? value : formatMoney(value, currency);
}

function formatDate(value: string | null): string | null {
  if (value === null) return null;
  const parsed = new Date(value);
  return Number.isNaN(parsed.getTime())
    ? null
    : parsed.toLocaleDateString('fr-FR', { day: 'numeric', month: 'long', year: 'numeric' });
}

/**
 * The review of an imported receipt (contract §6ter and §7). **No stock has been
 * written when this screen opens, and none is written until the last button.**
 *
 * Three things on this screen are not decoration.
 *
 * **The gap between the printed total and the sum of the lines is shown, in
 * figures.** `docs/technical-notes-ingestion.md` §3.4 measured, over 10 656
 * receipts, that vision models *fabricate or alter lines to force their sum onto
 * the printed total*; the line-item field peaks at 0.49 F1 while every other one
 * clears 0.85. So a receipt whose arithmetic falls out even proves nothing, and a
 * gap is the best signal available that a line was invented. Neither side ever
 * closes it — closing it would delete the signal to tidy a screen.
 *
 * **The budget rests on the total, the stock on the lines, and the screen says
 * so.** On the same photograph the money is more reliable than the inventory: it
 * depends on one number printed large instead of thirty small ones. A user who
 * does not know that will trust both equally, which is the wrong half.
 *
 * **How the lines were read is stated.** A drive recap's own text was not
 * generated by anything and cannot have been invented; a transcription of a
 * photograph can. The two do not deserve the same attention and the reader is
 * told which one they are looking at.
 */
export function ReceiptReview({ receipt, locations, onCancelled, onConfirmed }: Props) {
  const [lines, setLines] = useState<ReceiptDraftLine[]>(() => toReceiptDrafts(receipt.lines));
  const [locationId, setLocationId] = useState<string>(locations[0]?.id ?? '');
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const kept = lines.filter((line) => !line.removed);
  const invalidCount = kept.filter((line) => receiptDraftError(line) !== null).length;
  const withoutQuantity = kept.filter((line) => line.amount.trim() === '').length;
  const removedCount = lines.length - kept.length;

  const delta = receipt.line_sum_delta === null ? null : toCentimes(receipt.line_sum_delta);
  const purchasedOn = formatDate(receipt.purchased_at);

  const update = (id: string, next: ReceiptDraftLine): void => {
    setLines((current) => current.map((line) => (line.id === id ? next : line)));
  };

  const toggleRemoved = (id: string): void => {
    setLines((current) =>
      current.map((line) => (line.id === id ? { ...line, removed: !line.removed } : line)),
    );
  };

  const run = (task: Promise<void>): void => {
    setBusy(true);
    setError(null);
    task
      .catch((cause: unknown) => {
        setError(describeError(cause));
      })
      .finally(() => {
        setBusy(false);
      });
  };

  const confirm = (): void => {
    if (invalidCount > 0) return;
    run(
      confirmReceipt(
        receipt.id,
        toReceiptConfirmLines(lines),
        locationId === '' ? null : locationId,
      ).then(onConfirmed),
    );
  };

  const discard = (): void => {
    run(discardReceipt(receipt.id).then(onCancelled));
  };

  return (
    <section className={styles.review} aria-labelledby="receipt-review-heading">
      <div className={styles.reviewIntro}>
        <h2 className={styles.sectionTitle} id="receipt-review-heading">
          Vérifiez ce ticket
        </h2>
        <p className={styles.lead}>
          {receipt.merchant === null ? 'Enseigne non reconnue.' : `Ticket ${receipt.merchant}.`}{' '}
          {purchasedOn === null ? 'Date non lue.' : `Achat du ${purchasedOn}.`} Rien n’entre en
          stock tant que vous n’avez pas confirmé.
        </p>
      </div>

      {/*
        The totals panel, and the reason this screen exists in this shape. The two
        figures sit side by side precisely because they can disagree.
      */}
      <div className={styles.totals}>
        <div className={styles.total}>
          <span className={styles.totalLabel}>Total imprimé</span>
          <span className={styles.totalValue}>{money(receipt.total_amount, receipt.currency)}</span>
          <span className={styles.totalHint}>C’est ce montant qui compte dans le budget.</span>
        </div>
        <div className={styles.total}>
          <span className={styles.totalLabel}>Somme des lignes</span>
          <span className={styles.totalValue}>{money(receipt.line_sum, receipt.currency)}</span>
          <span className={styles.totalHint}>
            {receipt.line_sum === null
              ? 'Une ligne au moins n’a pas de prix : la somme n’est pas calculable.'
              : 'Calculée à partir des lignes lues ci-dessous.'}
          </span>
        </div>
      </div>

      {delta !== null && delta !== 0n ? (
        <Callout tone="warn" title="Le total et les lignes ne concordent pas">
          <p>
            {`L’écart est de ${money(receipt.line_sum_delta, receipt.currency)}. Il n’est pas corrigé, et c’est volontaire : c’est le meilleur indice qu’une ligne a été inventée, mal lue ou oubliée.`}
          </p>
          <p>
            Un écart n’est pas toujours une erreur — un sac, une remise ou une consigne peut
            l’expliquer. Le budget, lui, ne dépend que du total imprimé.
          </p>
        </Callout>
      ) : null}

      {receipt.read_by === 'model' ? (
        <Callout tone="info" title="Ces lignes ont été transcrites par un modèle">
          <p>
            Un modèle a lu la photo. Sur ce type de document, les <em>lignes</em> sont la partie la
            moins fiable : relisez-les, le total est bien plus sûr qu’elles.
          </p>
        </Callout>
      ) : (
        <p className={styles.note}>
          Ces lignes viennent du texte du PDF, pas d’une transcription : aucun modèle n’a été
          appelé, et rien n’a pu être inventé. Les colonnes ont pu être mal découpées, en revanche.
        </p>
      )}

      {receipt.truncated ? (
        <Callout tone="warn" title="Le ticket a été coupé">
          <p>
            Il contenait plus de lignes que Chaudron n’en lit en une fois. Le total imprimé reste
            juste ; les lignes manquantes n’entreront pas en stock.
          </p>
        </Callout>
      ) : null}

      {receipt.degradation_notice === null ? null : (
        <Callout tone="info" title="Lecture partielle">
          <p>{receipt.degradation_notice}</p>
        </Callout>
      )}

      {locations.length > 0 ? (
        <Field label="Ranger les articles dans" hint="Vous pourrez les déplacer ensuite.">
          {({ id, describedBy }) => (
            <select
              id={id}
              className={controlClass()}
              aria-describedby={describedBy}
              value={locationId}
              onChange={(event) => {
                setLocationId(event.target.value);
              }}
            >
              <option value="">— sans emplacement</option>
              {locations.map((location) => (
                <option key={location.id} value={location.id}>
                  {location.name}
                </option>
              ))}
            </select>
          )}
        </Field>
      ) : null}

      <ul className={styles.lineList}>
        {lines.map((line, index) => (
          <ReceiptLineRow
            key={line.id}
            line={line}
            position={index + 1}
            currency={receipt.currency}
            onChange={(next) => {
              update(line.id, next);
            }}
            onToggleRemoved={() => {
              toggleRemoved(line.id);
            }}
          />
        ))}
      </ul>

      {lines.length === 0 ? (
        <p className={styles.note}>
          Aucune ligne n’a pu être lue sur ce ticket. Le total, lui, est enregistré et compte dans
          votre budget — vous pouvez confirmer sans rien ajouter au stock, ou supprimer le ticket.
        </p>
      ) : null}

      {withoutQuantity > 0 ? (
        <p className={styles.note}>
          {`${String(withoutQuantity)} ${plural(withoutQuantity, 'ligne n’a pas de quantité et n’entrera pas en stock', 'lignes n’ont pas de quantité et n’entreront pas en stock')}. Une quantité inventée serait un stock faux ; complétez-les ou laissez-les de côté.`}
        </p>
      ) : null}

      {error !== null ? (
        <p className={styles.formError} role="alert">
          {error}
        </p>
      ) : null}

      {invalidCount > 0 ? (
        <p className={styles.note} role="status">
          {`${String(invalidCount)} ${plural(invalidCount, 'ligne est à corriger', 'lignes sont à corriger')} avant d’enregistrer.`}
        </p>
      ) : null}

      <div className={styles.reviewActions}>
        <Button variant="ghost" loading={busy} onClick={discard}>
          Supprimer ce ticket
        </Button>
        <Button variant="primary" loading={busy} disabled={invalidCount > 0} onClick={confirm}>
          {kept.length === 0
            ? 'Enregistrer le ticket'
            : `Enregistrer ${String(kept.length)} ${plural(kept.length, 'article', 'articles')}`}
        </Button>
      </div>

      {removedCount > 0 ? (
        <p className={styles.note}>
          {`${String(removedCount)} ${plural(removedCount, 'ligne retirée', 'lignes retirées')} du stock. ${plural(removedCount, 'Elle reste comptée', 'Elles restent comptées')} dans le total du ticket.`}
        </p>
      ) : null}
    </section>
  );
}
